// <auto-generated />
using System;
using Leaderboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leaderboard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929130346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leaderboard.Domain.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<long?>("MaxScore")
                        .HasColumnType("bigint")
                        .HasColumnName("max_score");

                    b.Property<long?>("MinScore")
                        .HasColumnType("bigint")
                        .HasColumnName("min_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<short>("ScoreOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("score_order");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_games_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_games_slug");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Games.GameApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_ciphertext");

                    b.HasKey("Id")
                        .HasName("pk_game_api_keys");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_api_keys_game_id");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("ix_game_api_keys_key_id");

                    b.ToTable("game_api_keys", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_players_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_players_username");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Players.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_refresh_tokens_player_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Scores.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<long>("BestScore")
                        .HasColumnType("bigint")
                        .HasColumnName("best_score");

                    b.Property<long>("RankKey")
                        .HasColumnType("bigint")
                        .HasColumnName("rank_key");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("score_id");

                    b.Property<int>("SubmissionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("submissions_count");

                    b.HasKey("GameId", "PlayerId")
                        .HasName("pk_leaderboard_entries");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_leaderboard_entries_player_id");

                    b.HasIndex("ScoreId")
                        .HasDatabaseName("ix_leaderboard_entries_score_id");

                    b.HasIndex("GameId", "RankKey", "AchievedAt", "PlayerId")
                        .HasDatabaseName("ix_leaderboard_entries_rank");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("GameId", "RankKey", "AchievedAt", "PlayerId"), new[] { "BestScore", "ScoreId" });

                    b.ToTable("leaderboard_entries", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Scores.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("nonce");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_scores_game_id");

                    b.HasIndex("ApiKeyId", "Nonce")
                        .IsUnique()
                        .HasDatabaseName("ux_scores_api_key_id_nonce");

                    b.HasIndex("PlayerId", "GameId", "SubmittedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_scores_player_id_game_id_submitted_at");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Infrastructure.ReadModels.LeaderboardStats", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<long>("PlayerCount")
                        .HasColumnType("bigint")
                        .HasColumnName("player_count");

                    b.HasKey("GameId")
                        .HasName("pk_leaderboard_stats");

                    b.ToTable("leaderboard_stats", (string)null);
                });

            modelBuilder.Entity("Leaderboard.Domain.Games.Game", b =>
                {
                    b.HasOne("Leaderboard.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_players_owner_id");
                });

            modelBuilder.Entity("Leaderboard.Domain.Games.GameApiKey", b =>
                {
                    b.HasOne("Leaderboard.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_api_keys_games_game_id");
                });

            modelBuilder.Entity("Leaderboard.Domain.Players.RefreshToken", b =>
                {
                    b.HasOne("Leaderboard.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_players_player_id");
                });

            modelBuilder.Entity("Leaderboard.Domain.Scores.LeaderboardEntry", b =>
                {
                    b.HasOne("Leaderboard.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_entries_games_game_id");

                    b.HasOne("Leaderboard.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_entries_players_player_id");

                    b.HasOne("Leaderboard.Domain.Scores.Score", null)
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_entries_scores_score_id");
                });

            modelBuilder.Entity("Leaderboard.Domain.Scores.Score", b =>
                {
                    b.HasOne("Leaderboard.Domain.Games.GameApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scores_game_api_keys_api_key_id");

                    b.HasOne("Leaderboard.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scores_games_game_id");

                    b.HasOne("Leaderboard.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scores_players_player_id");
                });

            modelBuilder.Entity("Leaderboard.Infrastructure.ReadModels.LeaderboardStats", b =>
                {
                    b.HasOne("Leaderboard.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_stats_games_game_id");
                });
#pragma warning restore 612, 618
        }
    }
}
